AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Parameters: 
  TableNameParameter: 
    Type: String
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: TransactionLogs
Resources:
  CreateTransactionLog:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: createLog.handler
        Runtime: nodejs12.x
        CodeUri: transactionCRUD/
        Description: >-
          Creates a new transaction log record, or updates an existing record with the same UUID.
        MemorySize: 512
        Timeout: 10
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TransactionLogs
        Events:
          CreateTransactionLog:
            Type: Api
            Properties:
              Path: /transaction
              Method: post

  GetTransactionLog:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: getLog.handler
        Runtime: nodejs12.x
        CodeUri: transactionCRUD/
        Description: >-
          Get a transaction log based on the UUID and timestamp
        MemorySize: 512
        Timeout: 10
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TransactionLogs
        Events:
          ReadTransactionLog:
            Type: Api
            Properties:
              Path: /transaction/{UUID}/{Timestamp}
              Method: get

  DeleteTransactionLog:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: deleteLog.handler
          Runtime: nodejs12.x
          CodeUri: transactionCRUD/
          Description: >-
            A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
          MemorySize: 512
          Timeout: 10
          Policies:
            - DynamoDBCrudPolicy:
                TableName: !Ref TransactionLogs
          Events:
            DeleteTransactionLog:
              Type: Api
              Properties:
                Path: /transaction/{UUID}/{Timestamp}
                Method: delete

  TransactionLogsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "UUID"
          AttributeType: "S"
        - 
          AttributeName: "Timestamp"
          AttributeType: "N"

      KeySchema: 
        - 
          AttributeName: "UUID"
          KeyType: "HASH"
        - 
          AttributeName: "Timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "TransactionLogs"
      