---
version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: black
          pkg-manager: pip
      - run:
          command: |
            black .
          name: Lint - Black
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python manage.py test --debug-mode
          name: Test
workflows:
  main:
    jobs:
      - build
