---
Resources:
  TransactionLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transaction-log-table 
      AttributeDefinitions: 
        - 
          AttributeName: "UUID"
          AttributeType: "S"
        - 
          AttributeName: "Timestamp"
          AttributeType: "N"

      KeySchema: 
        - 
          AttributeName: "UUID"
          KeyType: "HASH"
        - 
          AttributeName: "Timestamp"
          KeyType: "RANGE"
  APIHandler:
    Properties:
      Environment:
        Variables:
          TRANSACTION_LOG_TABLE:
            Ref: TransactionLogTable