---
# This workflow will run the Bandit security linter
# See https://github.com/PyCQA/bandit
name: Bandit

on:
  push:
    branches:
      - main
    paths:
      - '**.py'  # All markdown files in the repository
  pull_request:
    paths:
      - '**.py'

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Scan
        run: |
          pip install -r requirements-dev.txt
          bandit --exclude ./.venv/,./api/tests/ -r .
